id = "weft"
name = "Weft"
version = "0.1.0"
schema_version = 1
description = "Language support for Weft specification files"
authors = ["Intrinsic Labs"]
repository = "https://github.com/intrinsic-labs/weft"

[grammars.weft]
repository = "https://github.com/intrinsic-labs/weft"
rev = "ba63a8e7d80c71d53e36829141110072614535d2"
path = "packages/tree-sitter-weft"

[language_servers.weft-lsp]
name = "Weft Language Server"
languages = ["Weft"]
