id = "weft"
name = "Weft"
version = "0.1.0"
schema_version = 1
description = "Language support for Weft specification files"
authors = ["Intrinsic Labs"]
repository = "https://github.com/intrinsic-labs/weft"

[grammars.weft]
repository = "https://github.com/intrinsic-labs/weft"
rev = "14259a67858d780a3ecfbe05518df3716e2ea198"
path = "packages/tree-sitter-weft"

[language_servers.weft-lsp]
name = "Weft Language Server"
languages = ["Weft"]
